rovercode/rovercode

.gitmodules
The .gitmodules file will allow for recursive cloning and updating that will make getting all of the repositories a simpler process.
Cloning everything at once would be:
`git clone --recursive https://git.io/rovercode.git`
This addresses issue #31
=> Add .gitmodules file for managing submodules

rover-service/rover-service.py, www/app.py, www/js/blockly-api.js, www/js/mission-control.js, www/send-command.php
Added an API resource to the App.py`POST /api/v1/sendcommand`
=> [#26] Moved command queue into flask app

.gitmodules
=> Add Adafruit GPIO library as submodule

www/js/blockly-api.js, www/js/mission-control.js
=> Fix saving bds

Dockerfile, setup.sh, www/lighttpd.conf
Create a script to help with setting up the necessary dependencies for running the application. Right now the script will only work with Debian-based Linux distributions.
I have also updated the Dockerfile to keep it in sync.
This addresses issue #36.
=> Create setup script

www/app.py, www/js/rover-api.js
This addresses issue #39.
One thing that I noticed while doing this is that we have the `saved-bds` directory hardcoded a lot. I think we might want to either define it at the top or use a [flask configuration](http://flask.pocoo.org/docs/0.11/config/).
=> Migrate downloading of saved bd to flask

Dockerfile, README.md, setup.sh
Forgot to update the Dockerfile with my last pull request. Here it is.
=> Feature/27 migrate sensor events to flask (Dockerfile)

README.md
Apparently I missed committing some stuff to the README when I was setting up test.
=> Adds instructions for tests and switches to Slack for chat

setup.sh
The user must answer to continue. Also, it backs up their rc.local file in the case of something unintentional happening.
=> Changed autostart install script

.travis.yml, Dockerfile, setup.sh
Works around [this prospector problem](https://github.com/landscapeio/prospector/issues/206) until it is fixed.
=> Specify older version of pylint for prospector

setup.sh
I haven't tested this, but I think it's needed. See https://goo.gl/lDqXxr.
=> Without this, the system won't boot

Dockerfile, www/docs/build-a-rover.rst, www/docs/index.rst
Here is my first pass at instructions for building a rover.
Some things are not described in detail enough for a novice to succeed (e.g. rebuilding the kernel with the UVC driver). Hopefully, those steps will be circumvented in the future, so I didn't put a ton of effort into their instructions.
Let me know if you do see any major gaps, though!
=> Instructions for building a rover

.travis.yml, Dockerfile, setup.sh, www/requirements.txt
This moves our requirements to a requirements.txt. The motivation is that readthedocs can look for a requirements.txt file.
=> Use requirements.txt

www/app.py
Removes API endpoints that have moved to rovercode-web.
=> App clean up

.vscode/settings.json, README.md, www/app.py, www/tests/test_app.py
This make the rover use Oauth2 client_id/secret instead of username/pass to register with rovercode_web.
=> Use oauth2 creds

www/docs/contribute.rst
I edited our contributing landing page doc to:
* update stuff to be more accurate
* emphasize that we're friendly for code newbies
=> Improve contribute docs

rovercode/app.py, rovercode/constants.py, rovercode/tests/test_app.py
This makes changes to account for:
- The API change where Rover config is a JSON blob
- The API change where the Rover list results are paged
=> Update for rover config blob and paging

README.md
This adds a Zenhub badge, fixes a docs link, and updates the screeshot, which was broken.
=> Point to Zenhub and update screenshot

.gitmodules, Dockerfile, rovercode.service, setup.sh, start.sh
This is @rjfendricks and @ductape's work from Spring 2019 Hackday.
It adds the GrovePi drivers as a submodule, and adds then to the Dockerfile and setup.sh.
This also includes systemd setup.
=> Add GrovePi drivers

Dockerfile, README.md
* Reduces the size of the image by 200 MB
* Sets the command properly to allow for simpler alternative commands
* Updated README with simpler commands and information about pre-built image
* Added flags to the execution documentation to remove the container after running and to start it in daemon mode. This will make it easier on the user to not be stuck with stopped containers that throw errors when trying to start again this way.
=> Dockerfile optimization
